// Generated by tools/build_site.py.
window.siteSearch = {
  "en": {
    "entries": [
      {
        "title": "Home",
        "url": "index.html",
        "description": "Statistics and Data Science · UFSCar"
      },
      {
        "title": "Research",
        "url": "research.html",
        "description": "Statistics and Data Science · UFSCar"
      },
      {
        "title": "Projects",
        "url": "projects.html",
        "description": "Statistics and Data Science · UFSCar"
      },
      {
        "title": "Notes",
        "url": "notes.html",
        "description": "Statistics and Data Science · UFSCar"
      },
      {
        "title": "Presentations",
        "url": "presentations.html",
        "description": "Statistics and Data Science · UFSCar"
      },
      {
        "title": "Background",
        "url": "background.html",
        "description": "Statistics and Data Science · UFSCar"
      },
      {
        "title": "Contact",
        "url": "contact.html",
        "description": "Statistics and Data Science · UFSCar"
      },
      {
        "title": "Marketplace Promotions",
        "url": "projects.html#promotions",
        "description": "Match product spreadsheets to price lists and export promotion-ready prices for each marketplace. · Python Pandas Streamlit OpenPyXL"
      },
      {
        "title": "Random Forests & Graph Learning",
        "url": "projects.html#graph-learning",
        "description": "Research code for genomic data analysis, variable importance, and stability-based graph learning. · Python scikit-learn NumPy NetworkX"
      },
      {
        "title": "Mercado Livre Product Analysis",
        "url": "projects.html#marketplace-analysis",
        "description": "Collect listing information, compare products, and estimate net proceeds using the application’s fee assumptions. · Python Streamlit BeautifulSoup ReportLab"
      },
      {
        "title": "Genotype–Phenotype Graph Learning Using Random Forests and Stability Selection",
        "url": "research.html",
        "description": "CNPq · Random Forests · Variable importance · Stability selection · High-dimensional statistics · Graphical models"
      },
      {
        "title": "Statistical Programming",
        "url": "notes.html#statistical-programming-title",
        "description": "Thiago Rodrigo Ramos"
      },
      {
        "title": "Introduction to pandas",
        "url": "presentations.html#pandas-title",
        "description": "PET · pandas · NumPy · Matplotlib"
      },
      {
        "title": "View CV (PDF)",
        "url": "assets/cv.pdf",
        "description": "CV in English · PDF"
      }
    ],
    "ui": {
      "close": "Close",
      "label": "Page or topic",
      "placeholder": "e.g. graphs, projects, PET",
      "empty": "No results. Try another term.",
      "one": "result",
      "many": "results",
      "title": "Search this site"
    }
  },
  "pt": {
    "entries": [
      {
        "title": "Início",
        "url": "index.html",
        "description": "Estatística e Ciência de Dados · UFSCar"
      },
      {
        "title": "Pesquisa",
        "url": "research.html",
        "description": "Estatística e Ciência de Dados · UFSCar"
      },
      {
        "title": "Projetos",
        "url": "projects.html",
        "description": "Estatística e Ciência de Dados · UFSCar"
      },
      {
        "title": "Notas",
        "url": "notes.html",
        "description": "Estatística e Ciência de Dados · UFSCar"
      },
      {
        "title": "Apresentações",
        "url": "presentations.html",
        "description": "Estatística e Ciência de Dados · UFSCar"
      },
      {
        "title": "Trajetória",
        "url": "background.html",
        "description": "Estatística e Ciência de Dados · UFSCar"
      },
      {
        "title": "Contato",
        "url": "contact.html",
        "description": "Estatística e Ciência de Dados · UFSCar"
      },
      {
        "title": "Promoções para marketplaces",
        "url": "projects.html#promotions",
        "description": "Cruza planilhas de produtos com bases de preços e exporta os valores das promoções por marketplace. · Python Pandas Streamlit OpenPyXL"
      },
      {
        "title": "Florestas Aleatórias e grafos",
        "url": "projects.html#graph-learning",
        "description": "Código de pesquisa para análise de dados genômicos, importância de variáveis e aprendizado de grafos com seleção de estabilidade. · Python scikit-learn NumPy NetworkX"
      },
      {
        "title": "Análise de produtos do Mercado Livre",
        "url": "projects.html#marketplace-analysis",
        "description": "Reúne informações de anúncios, compara produtos e estima valores líquidos com as premissas de tarifas da aplicação. · Python Streamlit BeautifulSoup ReportLab"
      },
      {
        "title": "Aprendizado de grafos genótipo-fenótipo via Floresta Aleatória e seleção de estabilidade",
        "url": "research.html",
        "description": "CNPq · Florestas Aleatórias · Importância de variáveis · Seleção de estabilidade · Estatística em alta dimensão · Modelos gráficos"
      },
      {
        "title": "Programação Estatística",
        "url": "notes.html#statistical-programming-title",
        "description": "Thiago Rodrigo Ramos"
      },
      {
        "title": "Introdução ao pandas",
        "url": "presentations.html#pandas-title",
        "description": "PET · pandas · NumPy · Matplotlib"
      },
      {
        "title": "Ver CV (PDF)",
        "url": "../assets/cv.pdf",
        "description": "CV em inglês · PDF"
      }
    ],
    "ui": {
      "close": "Fechar",
      "label": "Página ou assunto",
      "placeholder": "Ex.: grafos, projetos, PET",
      "empty": "Nenhum resultado. Tente outro termo.",
      "one": "resultado",
      "many": "resultados",
      "title": "Buscar no site"
    }
  }
};
